# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_LIBS = PString 

# --- mega2560 ide 1.6
BOARD_TAG    = mega
BOARD_SUB    = atmega2560
#MONITOR_PORT = /dev/ttyACM0
#ARDUINO_DIR  = /where/you/installed/arduino-1.6.5
#AVRDUDE_ARD_PROGRAMMER = stk500v2
include $(ARDMK_DIR)/Arduino.mk
