# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

ARDUINO_LIBS = 
USR_INCLUDE = ./include

#BOARD_TAG    = uno
BOARD_TAG    = nano
BOARD_SUB    = atmega328
MONITOR_PORT = /dev/cu.wchusbserial1410
#MONITOR_PORT = /dev/ttyACM0
#ARDUINO_DIR  = /where/you/installed/arduino-1.6.5
#AVRDUDE_ARD_PROGRAMMER = stk500v2
include $(ARDMK_DIR)/Arduino.mk
